@ParametersAreNonnullByDefault
@MethodsReturnNonnullByDefault
package de.mineformers.investiture.client;

import mcp.MethodsReturnNonnullByDefault;

import javax.annotation.ParametersAreNonnullByDefault;