@ParametersAreNonnullByDefault
@MethodsReturnNonnullByDefault
package de.mineformers.investiture.client.renderer;

import mcp.MethodsReturnNonnullByDefault;

import javax.annotation.ParametersAreNonnullByDefault;