// generated by tscfg 0.2.1 on Sat Feb 13 14:31:46 CET 2016
// source: allomancy-config-def.conf

package de.mineformers.investiture.allomancy;

import com.typesafe.config.Config;

public class AllomancyConfig
{
    public final Mistings mistings;

    public static class Mistings
    {
        public final Thug thug;

        public static class Thug
        {
            public final double attackBoost;
            public final double damageResistance;

            public Thug(Config c)
            {
                this.attackBoost = c.hasPath("attackBoost") ? c.getDouble("attackBoost") : 6; // "double | 6"
                this.damageResistance = c.hasPath("damageResistance") ? c.getDouble("damageResistance") : 2.5; // "double | 2.5"
            }
        }

        public final Tineye tineye;

        public static class Tineye
        {
            public final boolean fovEnabled;
            public final float fovIncrease;
            public final float fovZoom;

            public Tineye(Config c)
            {
                this.fovEnabled = !c.hasPath("fovEnabled") || c.getBoolean("fovEnabled");
                this.fovIncrease = c.hasPath("fovIncrease") ? (float) c.getDouble("fovIncrease") : 40; // "double | 40"
                this.fovZoom = c.hasPath("fovZoom") ? (float) c.getDouble("fovZoom") : 10; // "double | 10"
            }
        }

        public Mistings(Config c)
        {
            this.thug = new Thug(c.getConfig("thug"));
            this.tineye = new Tineye(c.getConfig("tineye"));
        }
    }

    public AllomancyConfig(Config c)
    {
        this.mistings = new Mistings(c.getConfig("mistings"));
    }
}
