@ParametersAreNonnullByDefault
@MethodsReturnNonnullByDefault
package de.mineformers.investiture.allomancy.helper;

import mcp.MethodsReturnNonnullByDefault;

import javax.annotation.ParametersAreNonnullByDefault;