@ParametersAreNonnullByDefault
@MethodsReturnNonnullByDefault
package de.mineformers.investiture.api.multiblock;

import mcp.MethodsReturnNonnullByDefault;

import javax.annotation.ParametersAreNonnullByDefault;