@ParametersAreNonnullByDefault
@MethodsReturnNonnullByDefault
package de.mineformers.investiture.block.properties;

import mcp.MethodsReturnNonnullByDefault;

import javax.annotation.ParametersAreNonnullByDefault;